library(dplyr)
data <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
head(data)
sep_dates <- c("1/2/2007", "2/2/2007")
sep_data <- filter(data, Date %in% sep_dates)
head(sep_data)
data_inkw <- as.numeric(as.character(sep_data$Global_active_power))
hist(data_inkw, col = "red", main = paste("Global Active Power"), xlab = "Global Active Power (kilowatts)", col = "red")
dev.copy(png, file="plot1.png", width=480, height=480)
dev.off()
